version: '3'

services:

    postgres:
        image: postgres:15
        restart: unless-stopped
        environment:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
        volumes:
          - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data: {}