version: '3'

services:

    postgres:
        image: postgres:15
        restart: always
        environment:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
        volumes:
          - "pg_data:/var/lib/postgresql/data"

    backend:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      restart: always

volumes:
  pg_data: {}