# Generated by Django 4.2.4 on 2023-08-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, verbose_name="Номер телефона пользователя"
                    ),
                ),
                (
                    "check_code",
                    models.CharField(
                        max_length=4, verbose_name="Код авторизации пользователя"
                    ),
                ),
                (
                    "invite_key",
                    models.CharField(
                        max_length=6, verbose_name="Инвайт-код авторизации"
                    ),
                ),
                (
                    "referral_link",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="Реферальная ссылка пользователя",
                    ),
                ),
                (
                    "created_dt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создание пользователя"
                    ),
                ),
                (
                    "updated_dt",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Время последнего обновления пользователя",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
