# Generated by Django 4.2.4 on 2023-08-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_invite_key_alter_user_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invite_key",
            field=models.CharField(max_length=6, verbose_name="Инвайт-код авторизации"),
        ),
    ]
