# Generated by Django 4.2.4 on 2023-08-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_invite_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Номер телефона пользователя"
            ),
        ),
    ]
